=== AliaksandrNeuhen/JavaLab/xmltransforming/src/main/resources/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.shop.com/products" 
		xmlns:tns="http://www.shop.com/products" >

<element name="shop">
	<complexType>
		<sequence>
			<element name="category" type="tns:CategoryType"
				minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
</element>

<complexType name="CategoryType">
	<sequence>
		<element name="subcategory" type="tns:SubcategoryType"
			minOccurs="0" maxOccurs="unbounded"/>
	</sequence>
	<attribute type="string" name="name" use="required"/>
</complexType>

<complexType name="SubcategoryType">
	<sequence>
		<element name="product" type="tns:ProductType"
			minOccurs="0" maxOccurs="unbounded"/>
	</sequence>
	<attribute type="string" name="name" use="required"/>
</complexType>

<complexType name="ProductType">
	<sequence>
		<element name="provider" type="tns:ProviderType"/>
		<element name="model" type="tns:ModelType"/>
		<element name="date-of-issue" type="tns:DateOfIssueType"/>
		<element name="color" type="tns:ColorType"/>
		<choice>
			<element name="price" type="tns:PriceType"/>
			<element name="notinstock" type="tns:NotInStockType"/>
		</choice>
	</sequence>
	<attribute type="string" name="name" use="required"/>
</complexType>

<simpleType name="ProviderType">
	<restriction base="string"/>
</simpleType>

<simpleType name="ModelType">
	<restriction base="ID">
		<pattern value="[a-zA-Z]{2}[0-9]{3}"/>
	</restriction>
</simpleType>

<simpleType name="DateOfIssueType">
	<restriction base="string">
		<pattern value="[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]"/>
	</restriction>
</simpleType>

<simpleType name="ColorType">
	<restriction base="string"/>
</simpleType>

<simpleType name="PriceType">
	<restriction base="integer"/>
</simpleType>

<simpleType name="NotInStockType">
	<restriction base="string">
		<maxLength value="0"/>
	</restriction>
</simpleType>

</schema>

=== AliaksandrNeuhen/JavaLab/xmlwithjdom/src/main/resources/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products PUBLIC "products.dtd" "products.dtd">
<p:shop xmlns:p="http://www.shop.com/products"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://www.shop.com/products products.xsd">
<category name="Food">
	<subcategory name="Breadstuff">
		<product name="Long loaf">
			<provider>Minsk Plant Bakery</provider>
			<model>BS100</model>
			<date-of-issue>17-10-2014</date-of-issue>
			<color>White</color>
			<price>8000</price>
		</product>
		<product name="Black bread">
			<provider>Minsk Plant Bakery</provider>
			<model>BS200</model>
			<date-of-issue>17-10-2014</date-of-issue>
			<color>Black</color>
			<price>7000</price>
		</product>
	</subcategory>
	<subcategory name="Meat">
		<product name="Beef">
			<provider>Minsk Meat Processing Plant</provider>
			<model>MM100</model>
			<date-of-issue>17-10-2014</date-of-issue>
			<color>Red</color>
			<price>80000</price>
		</product>
	</subcategory>
	<subcategory name="Groats">
		<product name="Semolina">
			<provider>Minsk Plant Bakery</provider>
			<model>GG100</model>
			<date-of-issue>17-10-2014</date-of-issue>
			<color>White</color>
			<price>20000</price>
		</product>
	</subcategory>
</category>
<category name="Drinking">
	<subcategory name="Alcohol">
		<product name="Beer Alivaria">
			<provider>Alivaria plant</provider>
			<model>DB001</model>
			<date-of-issue>17-10-2014</date-of-issue>
			<color>Brown</color>
			<price>20000</price>
		</product>
	</subcategory>
	<subcategory name="Non-alcohol">
		<product name="Coca-Cola">
			<provider>Coca-Cola inc.</provider>
			<model>DN100</model>
			<date-of-issue>27-10-2014</date-of-issue>
			<color>Black</color>
			<price>14000</price>
		</product>
	</subcategory>
</category>
<category name="Household">
	<subcategory name="Hugiene">
		<product name="Toothbrush">
			<provider>Colgate</provider>
			<model>HT100</model>
			<date-of-issue>27-10-2014</date-of-issue>
			<color>White</color>
			<price>30000</price>
		</product>
		<product name="Soap">
			<provider>Dove</provider>
			<model>HS100</model>
			<date-of-issue>27-10-2014</date-of-issue>
			<color>White</color>
			<price>20000</price>
		</product>
	</subcategory>
</category>
</p:shop>
